baseURL: "https://yuzumone.github.io/pinocchio"
author: "yuzumone"
publishDir: "docs"
languageCode: "ja-jp"
title: "夢・見る・ピノキオ 音楽"
theme: "paper"
paginate: 10
disqusShortname: ""
googleAnalytics: G-FHLB36HZRC
